In [97]:
import pandas as pd
df = pd.read_csv("Amazon_Input.csv")
df

   ID Cus_Fname Agent_ID             Agent_name Cust_Satisfaction
0   1   Aravind      A11              Prim_chat                 Y
1   2  Baskaran      B22            Repeat_chat                 N
2   3     Cathy      C33            Direct_Mail                 N
3   4     David      D44            Fraud_Phone                 Y
4   5     Erica      E55       Prime_video_mail               NaN
5   6   Aravind      F66  Kindle_Unlimited_Mail                 N

# Question 1 - Count Unique ID

In [86]:
print(df['ID'].nunique()) #Counts distinct values excluding null values
print(df['Cust_Satisfaction'].nunique())
print(df['Cust_Satisfaction'].count()) #Counts non-null values
print(df['Cust_Satisfaction'].unique()) #To see the values in a column
print(df['Cust_Satisfaction'].size) #Counts null as well

6
2
5
['Y' 'N' nan]
6

# Question 2 - To Predict Cust_Sat , which column to use and which to leave

In [65]:
#According to me , We need to exclude Cus_Fname which has duplicate values and the main predictor is agent_name


# Question3 - Apart from One hot encoding, what technique can be applied

In [66]:
# First find the type-ordinal or nominal ; 
# Ordinal - Label Encoding (Sequence number is added for each category) 
# Nominal - OneHot(Uses 3 digits and creates n columns with binary) , 
# Nominal - Dummy(same as onehot but USes 2 digits and one variable is reduced) ,
# Effect - Same as dummy but uses -1,0,1
# HAsh - Hash Alg like MD5 will be app;ied and the no of dimensions can be selected but data is lost and also collision
#             Multiple values have same hash value is called collision
# Binary - Combination of one hot and Hash (cat -to ordinal to binary) suitable for large categories
# BaseN - Same like binary but we can pass the base value as 10 for decimal and respective number for octal
# Target - uses the mean value of the targle variable for each category and assigns to each category instead of 0 and 1 but 
#              leads to overfitting of the model

# Encoding Techniques

In [98]:
df_cat =pd.get_dummies(df['Agent_name'],drop_first=True)
df_cat
#!pip install category_encoders
#!pip install --upgrade pip
import category_encoders as aa #aa.tab will show all the encoder types
bb = aa.BaseNEncoder(cols=['Agent_name'])
df_neww = bb.fit_transform(df)
df_neww

,ID,Cus_Fname,Agent_ID,Agent_name_0,Agent_name_1,Agent_name_2,Cust_Satisfaction
0,1,Aravind,A11,0,0,1,Y
1,2,Baskaran,B22,0,1,0,N
2,3,Cathy,C33,0,1,1,N
3,4,David,D44,1,0,0,Y
4,5,Erica,E55,1,0,1,NaN
5,6,Aravind,F66,1,1,0,N

# We can split Agent_name into 2 cols

In [99]:
df[['Agent_type', 'Channel_used']] = df['Agent_name'].str.rsplit('_', 1, expand=True)
df

,ID,Cus_Fname,Agent_ID,Agent_name,Cust_Satisfaction,Agent_type,Channel_used
0,1,Aravind,A11,Prim_chat,Y,Prim,chat
1,2,Baskaran,B22,Repeat_chat,N,Repeat,chat
2,3,Cathy,C33,Direct_Mail,N,Direct,Mail
3,4,David,D44,Fraud_Phone,Y,Fraud,Phone
4,5,Erica,E55,Prime_video_mail,NaN,Prime_video,mail
5,6,Aravind,F66,Kindle_Unlimited_Mail,N,Kindle_Unlimited,Mail

# Combine ID and First name as 1 column

In [101]:
df['ID_name'] = df['ID'].map(str) + '_' + df['Cus_Fname'].map(str)
df

,ID,Cus_Fname,Agent_ID,Agent_name,Cust_Satisfaction,Agent_type,Channel_used,ID_name
0,1,Aravind,A11,Prim_chat,Y,Prim,chat,1_Aravind
1,2,Baskaran,B22,Repeat_chat,N,Repeat,chat,2_Baskaran
2,3,Cathy,C33,Direct_Mail,N,Direct,Mail,3_Cathy
3,4,David,D44,Fraud_Phone,Y,Fraud,Phone,4_David
4,5,Erica,E55,Prime_video_mail,NaN,Prime_video,mail,5_Erica
5,6,Aravind,F66,Kindle_Unlimited_Mail,N,Kindle_Unlimited,Mail,6_Aravind

In [104]:
#df.drop(columns=['Agent_name','ID','Cus_Fname'])
df

  Agent_ID Cust_Satisfaction        Agent_type Channel_used     ID_name
0      A11                 Y              Prim         chat   1_Aravind
1      B22                 N            Repeat         chat  2_Baskaran
2      C33                 N            Direct         Mail     3_Cathy
3      D44                 Y             Fraud        Phone     4_David
4      E55               NaN       Prime_video         mail     5_Erica
5      F66                 N  Kindle_Unlimited         Mail   6_Aravind

# Cust_Satisfaction is the target variable but there is a missing value
1) what are the imputation method and how do u choose btwn thwm?    
2) How to choose between mean and median imputation ?

# Imbalanced data Imputation techniques
1) how to choose between undersampling and over sampling ?                  
2) Where they(1) are applied ? Training , Testing or validation set ?                    
3) How to measure these techniques (1)                                                           
4) For imbalanced data , how to split the Yes or No data in the Train , test and validation set ?

# Model Performance comparsion if 5 models applied

# How to Prove or disaprove arguments placed by product person