In [141]:
#Creating dataframe
import pandas as pd
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN','londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )','12. Air France', '"Swiss Air"']})
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [142]:
#Ques1 - Missing value handle
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

In [49]:
#Ques 2 - Temporary dataframe
df['frm'] = df.From_To.apply(lambda x : x.split('_')[0])
df['to'] = df.From_To.apply(lambda x : x.split('_')[1])
temp = pd.concat([df['frm'], df['to']],axis=1)
#df.drop(columns=['frm','to'],inplace=True)
temp

        frm         to
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

In [50]:
#Ques 3 - Capitalise straings
temp.frm = temp.frm.str.capitalize()
temp.to = temp.to.str.capitalize()
temp

        frm         to
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

In [87]:
#Ques 4 - Delete From_To
df.drop(columns=['From_To'],inplace=True)
df = pd.concat([df,temp],axis=1)
df

,FlightNumber,Airline,Delay1,Delay2,Delay3,frm,to
0,10045.0,KLM(!),23.0,47.0,NaN,London,Paris
1,NaN,<Air France> (12),NaN,NaN,NaN,Madrid,Milan
2,10065.0,(British Airways. ),24.0,43.0,87.0,London,Stockholm
3,NaN,12. Air France,13.0,NaN,NaN,Budapest,Paris
4,10085.0,"""Swiss Air""",67.0,32.0,NaN,Brussels,London

In [86]:
#Question5 - Split list value into multiple cols

Delays = (pd.DataFrame(dfc.RecentDelays.tolist(),index =  dfc.index).
           rename(columns = lambda x : 'Delay{}'.format(x+1)))
Delays

   FlightNumber              Airline  Delay1  Delay2  Delay3
0       10045.0               KLM(!)    23.0    47.0     NaN
1           NaN    <Air France> (12)     NaN     NaN     NaN
2       10065.0  (British Airways. )    24.0    43.0    87.0
3           NaN       12. Air France    13.0     NaN     NaN
4       10085.0          "Swiss Air"    67.0    32.0     NaN

In [140]:
df

,FlightNumber,Airline,Delay1,Delay2,Delay3,frm,to
0,10045,KLM(!),23.0,47.0,NaN,London,Paris
1,10055,<Air France> (12),NaN,NaN,NaN,Madrid,Milan
2,10065,(British Airways. ),24.0,43.0,87.0,London,Stockholm
3,10075,12. Air France,13.0,NaN,NaN,Budapest,Paris
4,10085,"""Swiss Air""",67.0,32.0,NaN,Brussels,London