In [4]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=4)

In [65]:
df = pd.read_csv(r'C:\Users\Mirnalini\Downloads\examples\ex1.csv',names=['aa','bb','cc','dd','ee','ff'],na_values=['NULL'])
df

  aa  bb  cc  dd       ee  ff
0  a   b   c   d  message NaN
1  1   2   3   4    hello NaN
2  5   6   7   8    world NaN
3  9  10  11  12      foo NaN

In [24]:
df1 = pd.read_csv(r'C:\Users\Mirnalini\Downloads\examples\test.tsv',sep='\t')
df1

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [27]:
df.tail(1)

   a   b   c   d message
2  9  10  11  12     foo

In [47]:
df2 = pd.read_csv(r'C:\Users\Mirnalini\Downloads\examples\csv_mindex.csv',index_col=['key1','key2'])
df2

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [54]:
df3 = pd.read_csv(r'C:\Users\Mirnalini\Downloads\examples\ex4.csv',skiprows=[0,2,3])
df3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
import pandas as pd
df4 = pd.read_excel(r'C:\Users\Mirnalini\Downloads\examples\mi.xlsx',sheet_name='Sheet2',header=None,names=['a','b','c','d','e'])
df4

        a    b      c    d    e
0  edrejh  fer  ujhuj    j   jh
1      45    6    NaN    6    6
2      56    6    NaN    6    6
3      77  NaN    NaN    6   24
4     NaN    6    NaN  NaN  NaN

In [84]:
df5 = pd.read_html('https://www.basketball-reference.com/',skiprows=['1','2'])
len(df5)
df5[0].tail()

          East Unnamed: 1 Unnamed: 2   W   L
10  CHI x (11)          F          $  22  43
11  NYK x (12)          F          $  21  45
12  DET x (13)          F          $  20  46
13  ATL x (14)          F          $  20  47
14  CLE x (15)          F          $  19  46

In [98]:
df5[0].columns

Index(['East', 'Unnamed: 1', 'Unnamed: 2', 'W', 'L'], dtype='object')

In [108]:
df5[0].dtypes

East          object
Unnamed: 1    object
Unnamed: 2    object
W              int64
L              int64
dtype: object

In [112]:
dff = pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',sep=';')

In [113]:
dff

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
11,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
12,29,blue-collar,single,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
13,57,housemaid,divorced,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
14,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
15,54,retired,married,basic.9y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
16,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
17,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
18,50,blue-collar,married,basic.9y,no,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
19,39,management,single,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
20,30,unemployed,married,high.school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
21,55,blue-collar,married,basic.4y,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
22,55,retired,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
23,41,technician,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
24,37,admin.,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
25,35,technician,married,university.degree,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
26,59,technician,married,unknown,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
27,39,self-employed,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
28,54,technician,single,university.degree,unknown,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
29,55,unknown,married,university.degree,unknown,unknown,unknown,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41158,35,technician,divorced,basic.4y,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.035,4963.6,yes
41159,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,1,9,4,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41160,33,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.035,4963.6,yes
41161,33,admin.,married,university.degree,no,yes,no,cellular,nov,tue,...,1,999,1,failure,-1.1,94.767,-50.8,1.035,4963.6,no
41162,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
41163,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,3,4,2,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41164,54,admin.,married,professional.course,no,no,no,cellular,nov,tue,...,2,10,1,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41165,38,housemaid,divorced,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,yes
41166,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
41167,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41168,38,entrepreneur,married,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41169,62,services,married,high.school,no,yes,no,cellular,nov,wed,...,5,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41170,40,management,divorced,university.degree,no,yes,no,cellular,nov,wed,...,2,999,4,failure,-1.1,94.767,-50.8,1.030,4963.6,no
41171,33,student,married,professional.course,no,yes,no,telephone,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,yes
41172,31,admin.,single,university.degree,no,yes,no,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,yes
41173,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94.767,-50.8,1.031,4963.6,yes
41174,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,1,6,success,-1.1,94.767,-50.8,1.031,4963.6,yes
41175,34,student,single,unknown,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94.767,-50.8,1.031,4963.6,no
41176,38,housemaid,divorced,high.school,no,yes,yes,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,no
41177,57,retired,married,professional.course,no,yes,no,cellular,nov,thu,...,6,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,no
41178,62,retired,married,university.degree,no,no,no,cellular,nov,thu,...,2,6,3,success,-1.1,94.767,-50.8,1.031,4963.6,yes
41179,64,retired,divorced,professional.course,no,yes,no,cellular,nov,fri,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41180,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41181,37,admin.,married,university.degree,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41182,29,unemployed,single,basic.4y,no,yes,no,cellular,nov,fri,...,1,9,1,success,-1.1,94.767,-50.8,1.028,4963.6,no
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [114]:
dff.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [115]:
dff.tail(2)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [119]:
dff['age'].dtypes

dtype('int64')

In [121]:
dff.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [127]:
dff.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [126]:
dff.skip_rows['0']

AttributeError: 'DataFrame' object has no attribute 'skip_rows'

In [128]:
dff.rename(columns={'age':'Age'})

,Age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
11,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
12,29,blue-collar,single,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
13,57,housemaid,divorced,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
14,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
15,54,retired,married,basic.9y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
16,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
17,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
18,50,blue-collar,married,basic.9y,no,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
19,39,management,single,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
20,30,unemployed,married,high.school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
21,55,blue-collar,married,basic.4y,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
22,55,retired,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
23,41,technician,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
24,37,admin.,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
25,35,technician,married,university.degree,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
26,59,technician,married,unknown,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
27,39,self-employed,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
28,54,technician,single,university.degree,unknown,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
29,55,unknown,married,university.degree,unknown,unknown,unknown,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41158,35,technician,divorced,basic.4y,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.035,4963.6,yes
41159,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,1,9,4,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41160,33,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.035,4963.6,yes
41161,33,admin.,married,university.degree,no,yes,no,cellular,nov,tue,...,1,999,1,failure,-1.1,94.767,-50.8,1.035,4963.6,no
41162,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
41163,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,3,4,2,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41164,54,admin.,married,professional.course,no,no,no,cellular,nov,tue,...,2,10,1,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41165,38,housemaid,divorced,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,yes
41166,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
41167,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41168,38,entrepreneur,married,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41169,62,services,married,high.school,no,yes,no,cellular,nov,wed,...,5,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41170,40,management,divorced,university.degree,no,yes,no,cellular,nov,wed,...,2,999,4,failure,-1.1,94.767,-50.8,1.030,4963.6,no
41171,33,student,married,professional.course,no,yes,no,telephone,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,yes
41172,31,admin.,single,university.degree,no,yes,no,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,yes
41173,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94.767,-50.8,1.031,4963.6,yes
41174,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,1,6,success,-1.1,94.767,-50.8,1.031,4963.6,yes
41175,34,student,single,unknown,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94.767,-50.8,1.031,4963.6,no
41176,38,housemaid,divorced,high.school,no,yes,yes,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,no
41177,57,retired,married,professional.course,no,yes,no,cellular,nov,thu,...,6,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,no
41178,62,retired,married,university.degree,no,no,no,cellular,nov,thu,...,2,6,3,success,-1.1,94.767,-50.8,1.031,4963.6,yes
41179,64,retired,divorced,professional.course,no,yes,no,cellular,nov,fri,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41180,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41181,37,admin.,married,university.degree,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41182,29,unemployed,single,basic.4y,no,yes,no,cellular,nov,fri,...,1,9,1,success,-1.1,94.767,-50.8,1.028,4963.6,no
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [133]:
import pandas
pd.options.display.max_columns=10
dff

,age,job,marital,education,default,...,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,...,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,...,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,...,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,...,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,...,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,...,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,...,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,...,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,...,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,...,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,...,93.994,-36.4,4.857,5191.0,no
11,25,services,single,high.school,no,...,93.994,-36.4,4.857,5191.0,no
12,29,blue-collar,single,high.school,no,...,93.994,-36.4,4.857,5191.0,no
13,57,housemaid,divorced,basic.4y,no,...,93.994,-36.4,4.857,5191.0,no
14,35,blue-collar,married,basic.6y,no,...,93.994,-36.4,4.857,5191.0,no
15,54,retired,married,basic.9y,unknown,...,93.994,-36.4,4.857,5191.0,no
16,35,blue-collar,married,basic.6y,no,...,93.994,-36.4,4.857,5191.0,no
17,46,blue-collar,married,basic.6y,unknown,...,93.994,-36.4,4.857,5191.0,no
18,50,blue-collar,married,basic.9y,no,...,93.994,-36.4,4.857,5191.0,no
19,39,management,single,basic.9y,unknown,...,93.994,-36.4,4.857,5191.0,no
20,30,unemployed,married,high.school,no,...,93.994,-36.4,4.857,5191.0,no
21,55,blue-collar,married,basic.4y,unknown,...,93.994,-36.4,4.857,5191.0,no
22,55,retired,single,high.school,no,...,93.994,-36.4,4.857,5191.0,no
23,41,technician,single,high.school,no,...,93.994,-36.4,4.857,5191.0,no
24,37,admin.,married,high.school,no,...,93.994,-36.4,4.857,5191.0,no
25,35,technician,married,university.degree,no,...,93.994,-36.4,4.857,5191.0,no
26,59,technician,married,unknown,no,...,93.994,-36.4,4.857,5191.0,no
27,39,self-employed,married,basic.9y,unknown,...,93.994,-36.4,4.857,5191.0,no
28,54,technician,single,university.degree,unknown,...,93.994,-36.4,4.857,5191.0,no
29,55,unknown,married,university.degree,unknown,...,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...
41158,35,technician,divorced,basic.4y,no,...,94.767,-50.8,1.035,4963.6,yes
41159,35,technician,divorced,basic.4y,no,...,94.767,-50.8,1.035,4963.6,yes
41160,33,admin.,married,university.degree,no,...,94.767,-50.8,1.035,4963.6,yes
41161,33,admin.,married,university.degree,no,...,94.767,-50.8,1.035,4963.6,no
41162,60,blue-collar,married,basic.4y,no,...,94.767,-50.8,1.035,4963.6,no
41163,35,technician,divorced,basic.4y,no,...,94.767,-50.8,1.035,4963.6,yes
41164,54,admin.,married,professional.course,no,...,94.767,-50.8,1.035,4963.6,yes
41165,38,housemaid,divorced,university.degree,no,...,94.767,-50.8,1.030,4963.6,yes
41166,32,admin.,married,university.degree,no,...,94.767,-50.8,1.030,4963.6,yes
41167,32,admin.,married,university.degree,no,...,94.767,-50.8,1.030,4963.6,no
41168,38,entrepreneur,married,university.degree,no,...,94.767,-50.8,1.030,4963.6,no
41169,62,services,married,high.school,no,...,94.767,-50.8,1.030,4963.6,no
41170,40,management,divorced,university.degree,no,...,94.767,-50.8,1.030,4963.6,no
41171,33,student,married,professional.course,no,...,94.767,-50.8,1.031,4963.6,yes
41172,31,admin.,single,university.degree,no,...,94.767,-50.8,1.031,4963.6,yes
41173,62,retired,married,university.degree,no,...,94.767,-50.8,1.031,4963.6,yes
41174,62,retired,married,university.degree,no,...,94.767,-50.8,1.031,4963.6,yes
41175,34,student,single,unknown,no,...,94.767,-50.8,1.031,4963.6,no
41176,38,housemaid,divorced,high.school,no,...,94.767,-50.8,1.031,4963.6,no
41177,57,retired,married,professional.course,no,...,94.767,-50.8,1.031,4963.6,no
41178,62,retired,married,university.degree,no,...,94.767,-50.8,1.031,4963.6,yes
41179,64,retired,divorced,professional.course,no,...,94.767,-50.8,1.028,4963.6,no
41180,36,admin.,married,university.degree,no,...,94.767,-50.8,1.028,4963.6,no
41181,37,admin.,married,university.degree,no,...,94.767,-50.8,1.028,4963.6,yes
41182,29,unemployed,single,basic.4y,no,...,94.767,-50.8,1.028,4963.6,no
41183,73,retired,married,professional.course,no,...,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,...,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,...,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,...,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,...,94.767,-50.8,1.028,4963.6,no

In [142]:
import pandas as pd
pd.options.display.max_columns = 10
ff = pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',sep=';',chunksize=10)
ff

In [157]:
df5[0]

          East Unnamed: 1 Unnamed: 2   W   L
0    MIL * (1)          F          $  56  17
1    TOR * (2)          F          $  53  19
2    BOS * (3)          F          $  48  24
3    IND * (4)          F          $  45  28
4    MIA * (5)          F          $  44  29
5    PHI * (6)          F          $  43  30
6    BRK * (7)          F          $  35  37
7    ORL * (8)          F          $  33  40
8    CHO x (9)          F          $  23  42
9   WAS x (10)          F          $  25  47
10  CHI x (11)          F          $  22  43
11  NYK x (12)          F          $  21  45
12  DET x (13)          F          $  20  46
13  ATL x (14)          F          $  20  47
14  CLE x (15)          F          $  19  46

In [158]:
df5[0].to_csv('xyz.csv',index=False,columns=['East','W'])

In [19]:
dates = pd.date_range('1/1/2000',periods=7)

In [20]:
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [27]:
import numpy as np
import pandas as pd
df = pd.Series(np.arange(7),index=['mir','1','e','5','5','5','9'])
type(df)
df

mir    0
1      1
e      2
5      3
5      4
5      5
9      6
dtype: int32

In [2]:
import numpy as np
import pandas as pd
df = pd.Series(np.arange(7),index=dates)
type(df)
df

NameError: name 'dates' is not defined

In [30]:
import csv

In [35]:
o = open('xyz.csv')
p = csv.reader(o)

In [38]:
type(p)

_csv.reader

In [39]:
for i in p:
    print(i)

In [44]:
l1 = [5,78,4,8,9,0]    
l2 = [1,8,4,3,9]
list(zip(l1,l2))

[(5, 1), (78, 8), (4, 4), (8, 3), (9, 9)]

In [47]:
s = pd.read_json(r'C:\Users\Mirnalini\Downloads\examples\example.json')

In [49]:
s

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [86]:
import requests
resp = requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')
type(resp)

requests.models.Response

In [87]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35767',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35767/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35767/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35767/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35767',
  'id': 680175748,
  'node_id': 'MDU6SXNzdWU2ODAxNzU3NDg=',
  'number': 35767,
  'title': 'BUG: datetime ExtensionDtype do not work with DataFrame',
  'user': {'login': 'marco-neumann-by',
   'id': 57095103,
   'node_id': 'MDQ6VXNlcjU3MDk1MTAz',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/57095103?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/marco-neumann-by',
   'html_url': 'https://github.com/marco-neumann-by',
   'followers_url': 'https://api.github.com/users/marco-neumann-by/followers',
   'following_url': 'https://api.github.com/users/marco-neumann-by/following{/other_user}',
   'gists_url': 'https://api.github.com/users/marco-neumann-by/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/marco-neumann-by/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/marco-neumann-by/subscriptions',
   'organizations_url': 'https://api.github.com/users/marco-neumann-by/orgs',
   'repos_url': 'https://api.github.com/users/marco-neumann-by/repos',
   'events_url': 'https://api.github.com/users/marco-neumann-by/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/marco-neumann-by/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-17T11:52:37Z',
  'updated_at': '2020-08-17T11:52:37Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '- [x] I have checked that this issue has not already been reported. (at least I couldn\'t find one)\r\n\r\n- [X] I have confirmed this bug exists on the latest version of pandas. (1.1.0)\r\n\r\n- [X] (optional) I have confirmed this bug exists on the master branch of pandas. (`934e9f840ebd2e8b5a5181b19a23e033bd3985a5`)\r\n\r\n---\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\nThis is some high-level example that lead to the investion. It relies on [`rle-array`](https://github.com/JDASoftwareGroup/rle-array/) (commit `dfa79295a580d533ee9d2ea901e8808496dbcdc9` was used), because the pandas-provided [`DatetimeArray`](https://github.com/pandas-dev/pandas/blob/934e9f840ebd2e8b5a5181b19a23e033bd3985a5/pandas/core/arrays/datetimes.py#L116) uses a NumPy dtype or `DatetimeTZDtype`. Both cases somewhat work (see "Problem description").\r\n\r\n```python\r\nimport pandas as pd\r\nfrom rle_array import RLEArray\r\n\r\narray = RLEArray._from_sequence([], dtype="datetime64[ns]")\r\ndf = pd.DataFrame({"x": array})\r\n```\r\n\r\n```text\r\nTraceback (most recent call last):\r\n  File "bug.py", line 5, in <module>\r\n    pd.DataFrame({"x": array})\r\n  File ".../lib/python3.8/site-packages/pandas/core/frame.py", line 467, in __init__\r\n    mgr = init_dict(data, index, columns, dtype=dtype)\r\n  File ".../lib/python3.8/site-packages/pandas/core/internals/construction.py", line 283, in init_dict\r\n    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)\r\n  File ".../lib/python3.8/site-packages/pandas/core/internals/construction.py", line 93, in arrays_to_mgr\r\n    return create_block_manager_from_arrays(arrays, arr_names, axes)\r\n  File ".../lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1650, in create_block_manager_from_arrays\r\n    blocks = form_blocks(arrays, names, axes)\r\n  File ".../lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1703, in form_blocks\r\n    block_type = get_block_type(v)\r\n  File ".../lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 2672, in get_block_type\r\n    assert not is_datetime64tz_dtype(values.dtype)\r\nAssertionError\r\n```\r\n\r\n#### Problem description\r\n\r\nSee here:\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/934e9f840ebd2e8b5a5181b19a23e033bd3985a5/pandas/core/internals/blocks.py#L2647-L2690\r\n\r\ndatetime (and also interval) types are checked BEFORE extension types which means that extension datetime types never end up in `ExtensionBlock`s. The latter one would be useful if:\r\n\r\n- the datetime objects is not compatible with NumPy\r\n- the data should not be converted to to NumPy (e.g. due to compression, like in the `rle-array` case)\r\n\r\nFurthermore the invariant `issubclass(vtype, np.datetime64) => not is_datetime64tz_dtype(values.dtype)` does NOT hold for all extension dtypes, at least not under the current implementation of `is_datetime64tz_dtype`:\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/934e9f840ebd2e8b5a5181b19a23e033bd3985a5/pandas/core/dtypes/common.py#L415-L421\r\n\r\n#### Expected Output\r\n\r\nThe code example works and `df._data` shows that the data ends up in an `ExtensionBlock`.\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : d9fff2792bf16178d4e450fe7384244e50635733\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.6.0\r\nVersion          : Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : en_US.UTF-8\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 47.1.0\r\nCython           : None\r\npytest           : 6.0.1\r\nhypothesis       : None\r\nsphinx           : 3.2.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.2\r\nIPython          : 7.16.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : 0.50.1\r\n```\r\n\r\n</details>\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35766',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35766/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35766/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35766/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35766',
  'id': 680158314,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDY4NzY3OTQ4',
  'number': 35766,
  'title': 'Revert "REGR: Fix interpolation on empty dataframe"',
  'user': {'login': 'simonjayhawkins',
   'id': 13159005,
   'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/13159005?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/simonjayhawkins',
   'html_url': 'https://github.com/simonjayhawkins',
   'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
   'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
   'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
   'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
   'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
   'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-17T11:21:11Z',
  'updated_at': '2020-08-17T11:21:11Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35766',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35766',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35766.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35766.patch'},
  'body': 'Reverts pandas-dev/pandas#35543',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35765',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35765/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35765/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35765/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35765',
  'id': 680145801,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDY4NzU4NTg5',
  'number': 35765,
  'title': "Backport PR #35697 on branch 1.1.x (REGR: Don't ignore compiled patterns in replace)",
  'user': {'login': 'meeseeksmachine',
   'id': 39504233,
   'node_id': 'MDQ6VXNlcjM5NTA0MjMz',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/39504233?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/meeseeksmachine',
   'html_url': 'https://github.com/meeseeksmachine',
   'followers_url': 'https://api.github.com/users/meeseeksmachine/followers',
   'following_url': 'https://api.github.com/users/meeseeksmachine/following{/other_user}',
   'gists_url': 'https://api.github.com/users/meeseeksmachine/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/meeseeksmachine/subscriptions',
   'organizations_url': 'https://api.github.com/users/meeseeksmachine/orgs',
   'repos_url': 'https://api.github.com/users/meeseeksmachine/repos',
   'events_url': 'https://api.github.com/users/meeseeksmachine/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/meeseeksmachine/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 57522093,
    'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings',
    'name': 'Strings',
    'color': '5319e7',
    'default': False,
    'description': 'String extension data type and string data'},
   {'id': 1652721180,
    'node_id': 'MDU6TGFiZWwxNjUyNzIxMTgw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/replace',
    'name': 'replace',
    'color': '01a886',
    'default': False,
    'description': 'replace method'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/75',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/75',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/75/labels',
   'id': 5640672,
   'node_id': 'MDk6TWlsZXN0b25lNTY0MDY3Mg==',
   'number': 75,
   'title': '1.1.1',
   'description': 'on-merge: backport to 1.1.x',
   'creator': {'login': 'jreback',
    'id': 953992,
    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/jreback',
    'html_url': 'https://github.com/jreback',
    'followers_url': 'https://api.github.com/users/jreback/followers',
    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',
    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',
    'organizations_url': 'https://api.github.com/users/jreback/orgs',
    'repos_url': 'https://api.github.com/users/jreback/repos',
    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/jreback/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 31,
   'closed_issues': 88,
   'state': 'open',
   'created_at': '2020-07-10T13:54:44Z',
   'updated_at': '2020-08-17T11:25:13Z',
   'due_on': '2020-08-22T07:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2020-08-17T11:00:57Z',
  'updated_at': '2020-08-17T11:23:22Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35765',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35765',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35765.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35765.patch'},
  'body': "Backport PR #35697: REGR: Don't ignore compiled patterns in replace",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35763',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35763/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35763/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35763/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35763',
  'id': 680099857,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDY4NzIwNDg4',
  'number': 35763,
  'title': 'MAINT: Initialize year to silence warning',
  'user': {'login': 'bashtage',
   'id': 5585221,
   'node_id': 'MDQ6VXNlcjU1ODUyMjE=',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/5585221?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bashtage',
   'html_url': 'https://github.com/bashtage',
   'followers_url': 'https://api.github.com/users/bashtage/followers',
   'following_url': 'https://api.github.com/users/bashtage/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bashtage/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bashtage/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bashtage/subscriptions',
   'organizations_url': 'https://api.github.com/users/bashtage/orgs',
   'repos_url': 'https://api.github.com/users/bashtage/repos',
   'events_url': 'https://api.github.com/users/bashtage/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bashtage/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-17T09:47:13Z',
  'updated_at': '2020-08-17T09:47:13Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35763',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35763',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35763.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35763.patch'},
  'body': 'Initialize year to silence warning due to subtracting from\r\nvalue that compiler cannot reason must be either initialized\r\nor never reached\r\n\r\ncloses #35622\r\n\r\n- [X] closes #35622\r\n- [X] passes `black pandas`\r\n- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35762',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35762/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35762/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35762/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35762',
  'id': 680074629,
  'node_id': 'MDU6SXNzdWU2ODAwNzQ2Mjk=',
  'number': 35762,
  'title': 'BUG: Sparse[datetime64[ns]] TypeError: data type not understood',
  'user': {'login': 'sbrugman',
   'id': 9756388,
   'node_id': 'MDQ6VXNlcjk3NTYzODg=',
   'avatar_url': 'https://avatars2.githubusercontent.com/u/9756388?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/sbrugman',
   'html_url': 'https://github.com/sbrugman',
   'followers_url': 'https://api.github.com/users/sbrugman/followers',
   'following_url': 'https://api.github.com/users/sbrugman/following{/other_user}',
   'gists_url': 'https://api.github.com/users/sbrugman/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/sbrugman/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/sbrugman/subscriptions',
   'organizations_url': 'https://api.github.com/users/sbrugman/orgs',
   'repos_url': 'https://api.github.com/users/sbrugman/repos',
   'events_url': 'https://api.github.com/users/sbrugman/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/sbrugman/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 49182326,
    'node_id': 'MDU6TGFiZWw0OTE4MjMyNg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Sparse',
    'name': 'Sparse',
    'color': '009800',
    'default': False,
    'description': 'Sparse Data Type'},
   {'id': 211840,
    'node_id': 'MDU6TGFiZWwyMTE4NDA=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries',
    'name': 'Timeseries',
    'color': 'AFEEEE',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',
   'id': 933188,
   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',
   'number': 32,
   'title': 'Contributions Welcome',

pandas.core.frame.DataFrame

Empty DataFrame
Columns: [a, b, c, d, e, f, g]
Index: []

In [93]:
    sub = pd.DataFrame(data[i]['labels'],columns=['a','b','c','d','e','f','g'])
    m1 = m1.append(sub,ignore_index=True)

In [94]:
m1

      a    b    c    d    e    f    g
0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN  NaN  NaN  NaN  NaN
18  NaN  NaN  NaN  NaN  NaN  NaN  NaN
19  NaN  NaN  NaN  NaN  NaN  NaN  NaN
20  NaN  NaN  NaN  NaN  NaN  NaN  NaN
21  NaN  NaN  NaN  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN  NaN  NaN  NaN  NaN
23  NaN  NaN  NaN  NaN  NaN  NaN  NaN
24  NaN  NaN  NaN  NaN  NaN  NaN  NaN
25  NaN  NaN  NaN  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN  NaN  NaN  NaN  NaN
27  NaN  NaN  NaN  NaN  NaN  NaN  NaN
28  NaN  NaN  NaN  NaN  NaN  NaN  NaN
29  NaN  NaN  NaN  NaN  NaN  NaN  NaN
30  NaN  NaN  NaN  NaN  NaN  NaN  NaN
31  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN  NaN  NaN  NaN  NaN
33  NaN  NaN  NaN  NaN  NaN  NaN  NaN
34  NaN  NaN  NaN  NaN  NaN  NaN  NaN
35  NaN  NaN  NaN  NaN  NaN  NaN  NaN
36  NaN  NaN  NaN  NaN  NaN  NaN  NaN
37  NaN  NaN  NaN  NaN  NaN  NaN  NaN
38  NaN  NaN  NaN  NaN  NaN  NaN  NaN
39  NaN  NaN  NaN  NaN  NaN  NaN  NaN
40  NaN  NaN  NaN  NaN  NaN  NaN  NaN
41  NaN  NaN  NaN  NaN  NaN  NaN  NaN
42  NaN  NaN  NaN  NaN  NaN  NaN  NaN
43  NaN  NaN  NaN  NaN  NaN  NaN  NaN
44  NaN  NaN  NaN  NaN  NaN  NaN  NaN
45  NaN  NaN  NaN  NaN  NaN  NaN  NaN