import json
data = {'result' :
[{
'sd': 'sGer is 2345r throwing ',
'value': '#f00',
'INC_NO' : '1',
'resolution' : 'Change "Y" to N '
},
{
'sd': 'sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing ',
'value': '#0f0',
    'INC_NO' : '2',
'resolution' : "P;ease provde a proper value and Enter 'Y' to N "
},
{
'sd': 'SGLC1 complife policy is not getting processed and facing 7865R SGVB',
'value': '#00f',
'INC_NO' : '3',
'resolution' : 'Enter correct premium '
},
{
'sd': " THrows 6533R character of 234 parsemant error in sgre ",
'value': '#0ff',
'INC_NO' : '4',
'resolution' : 'Withdraw the transaction'
},
{
'sd': " GOT STRUCK in SGlr ASGAPssss and Process 1 is incomplete by getting 1263R",
'value': '#0ff',
'INC_NO' : '5',
    'resolution' : 'Cancel and start from Beginning'
},
{
'sd': "In screen of SGRE,THrows 5945r character of parsemant error",
'value': '#0ff',
'INC_NO' : '6',
'resolution' : 'Process SGAP Screen'
},
{
'sd': "A LOT of errors happening at 6754r  SGHF",
'value': '#0ff',
'INC_NO' : '7',
    'resolution' : 'Server issue, so try after sometime '
},
{
'sd': 'SGAA is facing Err code of 7635R',
'value': '#0ff',
    'INC_NO' : '8',
'resolution' : 'Server issue, so try after sometime '
}
]
}

In [1]:
pwd

'C:\\Users\\Mirnalini'

In [4]:
import pandas as pd
df = pd.DataFrame(data['result'])
df

,sd,value,INC_NO,resolution
0,sGer is 2345r throwing,#f00,1,"Change ""Y"" to N"
1,sGer is 2345r throwing error ! 2345R help! i a...,#0f0,2,P;ease provde a proper value and Enter 'Y' to N
2,SGLC1 complife policy is not getting processed...,#00f,3,Enter correct premium
3,THrows 6533R character of 234 parsemant error...,#0ff,4,Withdraw the transaction
4,GOT STRUCK in SGlr ASGAPssss and Process 1 is...,#0ff,5,Cancel and start from Beginning
5,"In screen of SGRE,THrows 5945r character of pa...",#0ff,6,Process SGAP Screen
6,A LOT of errors happening at 6754r SGHF,#0ff,7,"Server issue, so try after sometime"
7,SGAA is facing Err code of 7635R,#0ff,8,"Server issue, so try after sometime"

In [3]:
import json
data = {'result' :
[{
'sd': 'sGer is 2345r throwing ',
'value': '#f00',
'INC_NO' : '1',
'resolution' : 'Change "Y" to N '
},
{
'sd': 'sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing ',
'value': '#0f0',
    'INC_NO' : '2',
'resolution' : "P;ease provde a proper value and Enter 'Y' to N "
},
{
'sd': 'SGLC1 complife policy is not getting processed and facing 7865R SGVB',
'value': '#00f',
'INC_NO' : '3',
'resolution' : 'Enter correct premium '
},
{
'sd': " THrows 6533R character of 234 parsemant error in sgre ",
'value': '#0ff',
'INC_NO' : '4',
'resolution' : 'Withdraw the transaction'
},
{
'sd': " GOT STRUCK in SGlr ASGAPssss and Process 1 is incomplete by getting 1263R",
'value': '#0ff',
'INC_NO' : '5',
    'resolution' : 'Cancel and start from Beginning'
},
{
'sd': "In screen of SGRE,THrows 5945r character of parsemant error",
'value': '#0ff',
'INC_NO' : '6',
'resolution' : 'Process SGAP Screen'
},
{
'sd': "A LOT of errors happening at 6754r  SGHF",
'value': '#0ff',
'INC_NO' : '7',
    'resolution' : 'Server issue, so try after sometime '
},
{
'sd': 'SGAA is facing Err code of 7635R',
'value': '#0ff',
    'INC_NO' : '8',
'resolution' : 'Server issue, so try after sometime '
}
]
}

In [9]:
#Creating new dic with only required fields
new_dic = dict()
for i in data['result']:
    txt = i['sd']
    res = i['resolution']
    new_dic[txt] = res
aa = list(new_dic.items())
new_dic

{'sGer is 2345r throwing ': 'Change "Y" to N ',
 'sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing ': "P;ease provde a proper value and Enter 'Y' to N ",
 'SGLC1 complife policy is not getting processed and facing 7865R SGVB': 'Enter correct premium ',
 ' THrows 6533R character of 234 parsemant error in sgre ': 'Withdraw the transaction',
 ' GOT STRUCK in SGlr ASGAPssss and Process 1 is incomplete by getting 1263R': 'Cancel and start from Beginning',
 'In screen of SGRE,THrows 5945r character of parsemant error': 'Process SGAP Screen',
 'A LOT of errors happening at 6754r  SGHF': 'Server issue, so try after sometime ',
 'SGAA is facing Err code of 7635R': 'Server issue, so try after sometime '}

In [3]:
#creating dataframe
import pandas as pd
import re
pd.options.display.max_colwidth=100
df = pd.DataFrame(data = aa,columns=['Description','Resolution'])
df

,Description,Resolution
0,sGer is 2345r throwing,"Change ""Y"" to N"
1,sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing,"P;ease provde a proper value and Enter ""Y"" to N"
2,SGLC1 complife policy is not getting processed and facing 7865R SGVB,Enter correct premium
3,THrows 6533R character of 234 parsemant error in sgre,Withdraw the transaction
4,GOT STRUCK in SGlr ASGAPssss and Process 1 is incomplete by getting 1263R,Cancel and start from Beginning
5,"In screen of SGRE,THrows 5945r character of parsemant error",Process SGAP Screen
6,A LOT of errors happening at 6754r SGHF,"Server issue, so try after sometime"
7,SGAA is facing Err code of 7635R,"Server issue, so try after sometime"

In [4]:
#Extracting screen name

def func_ex(pat,lst):
    
    sub_lst = []
       
    sear = re.findall(pat,lst,re.IGNORECASE)

    if sear == None:
        return np.nan
    else:
        sub_lst = [i for i,j in sear]
        return sub_lst
    
pattern1 = r'((sg)[a-zA-Z]{2})'

pattern2 = r'[0-9]{4}[R|r]'

df['Scr_new'] = df['Description'].apply(lambda i:func_ex(pattern1,i))

In [5]:
#Extracting error code

def func_ex1(pat,lst):
    
    sub_lst1 = []
    sear = re.findall(pat,lst)
    
    if sear == None:
        return np.nan
    else:
        return sear

pattern2 = r'[0-9]{4}[R|r]'


df['err_new'] = df['Description'].apply(lambda i:func_ex1(pattern2,i))

In [6]:
#Capitalise elements in list
def capill(r):
    
    newz=[]
    map_object = map(str.upper,r)     
    newz = list(map_object)
    return newz

df.Scr_new = df.Scr_new.apply(capill)
df.err_new = df.err_new.apply(capill)

In [7]:
#Duplicate removal of elements in list
import numpy as pd
df.Scr_new = df.Scr_new.map(pd.unique)
df.err_new = df.err_new.map(pd.unique)

In [8]:

#df

,Description,Resolution,Scr_new,err_new
0,sGer is 2345r throwing,"Change ""Y"" to N",[SGER],[2345R]
1,sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing,"P;ease provde a proper value and Enter ""Y"" to N",[SGER],[2345R]
2,SGLC1 complife policy is not getting processed and facing 7865R SGVB,Enter correct premium,"[SGLC, SGVB]",[7865R]
3,THrows 6533R character of 234 parsemant error in sgre,Withdraw the transaction,[SGRE],[6533R]
4,GOT STRUCK in SGlr ASGAPssss and Process 1 is incomplete by getting 1263R,Cancel and start from Beginning,"[SGAP, SGLR]",[1263R]
5,"In screen of SGRE,THrows 5945r character of parsemant error",Process SGAP Screen,[SGRE],[5945R]
6,A LOT of errors happening at 6754r SGHF,"Server issue, so try after sometime",[SGHF],[6754R]
7,SGAA is facing Err code of 7635R,"Server issue, so try after sometime",[SGAA],[7635R]

In [9]:
df1 = df.copy()
df1

,Description,Resolution,Scr_new,err_new
0,sGer is 2345r throwing,"Change ""Y"" to N",[SGER],[2345R]
1,sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing,"P;ease provde a proper value and Enter ""Y"" to N",[SGER],[2345R]
2,SGLC1 complife policy is not getting processed and facing 7865R SGVB,Enter correct premium,"[SGLC, SGVB]",[7865R]
3,THrows 6533R character of 234 parsemant error in sgre,Withdraw the transaction,[SGRE],[6533R]
4,GOT STRUCK in SGlr ASGAPssss and Process 1 is incomplete by getting 1263R,Cancel and start from Beginning,"[SGAP, SGLR]",[1263R]
5,"In screen of SGRE,THrows 5945r character of parsemant error",Process SGAP Screen,[SGRE],[5945R]
6,A LOT of errors happening at 6754r SGHF,"Server issue, so try after sometime",[SGHF],[6754R]
7,SGAA is facing Err code of 7635R,"Server issue, so try after sometime",[SGAA],[7635R]

In [10]:
df1['Scr_new'].value_counts()

TypeError: unhashable type: 'numpy.ndarray'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'numpy.ndarray'

[SGRE]          2
[SGHF]          1
[SGER]          1
[SGER]          1
[SGAA]          1
[SGAP, SGLR]    1
[SGLC, SGVB]    1
Name: Scr_new, dtype: int64

In [11]:
df1['err_new'].value_counts()

TypeError: unhashable type: 'numpy.ndarray'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'numpy.ndarray'

[5945R]    1
[2345R]    1
[2345R]    1
[6754R]    1
[1263R]    1
[6533R]    1
[7865R]    1
[7635R]    1
Name: err_new, dtype: int64

In [12]:
df1.iloc[6]

Description    A LOT of errors happening at 6754r  SGHF
Resolution         Server issue, so try after sometime
Scr_new                                          [SGHF]
err_new                                         [6754R]
Name: 6, dtype: object

In [13]:
df['lg'] = df['Scr_new'].apply(lambda c : len(c))

In [14]:
df_n = df[df['lg'] < 2]

In [15]:
df_n

,Description,Resolution,Scr_new,err_new,lg
0,sGer is 2345r throwing,"Change ""Y"" to N",[SGER],[2345R],1
1,sGer is 2345r throwing error ! 2345R help! i am worried.....y is not enabling and facing,"P;ease provde a proper value and Enter ""Y"" to N",[SGER],[2345R],1
3,THrows 6533R character of 234 parsemant error in sgre,Withdraw the transaction,[SGRE],[6533R],1
5,"In screen of SGRE,THrows 5945r character of parsemant error",Process SGAP Screen,[SGRE],[5945R],1
6,A LOT of errors happening at 6754r SGHF,"Server issue, so try after sometime",[SGHF],[6754R],1
7,SGAA is facing Err code of 7635R,"Server issue, so try after sometime",[SGAA],[7635R],1

In [16]:
df_n.drop(columns=['lg'],inplace=True)
df_n.drop(columns=['Description'],inplace=True)
df_n

C:\Users\Mirnalini\Anaconda3\lib\site-packages\pandas\core\frame.py:4169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                                         Resolution Scr_new  err_new
0                                  Change "Y" to N   [SGER]  [2345R]
1  P;ease provde a proper value and Enter "Y" to N   [SGER]  [2345R]
3                          Withdraw the transaction  [SGRE]  [6533R]
5                               Process SGAP Screen  [SGRE]  [5945R]
6              Server issue, so try after sometime   [SGHF]  [6754R]
7              Server issue, so try after sometime   [SGAA]  [7635R]

In [71]:
corps

0    SGER 2345R
1    SGER 2345R
2    SGRE 6533R
3    SGRE 5945R
4    SGHF 6754R
5    SGAA 7635R
Name: corp, dtype: object

In [68]:
df_n['corp'] = df_n['Scr_new'].apply(lambda l:l.tolist()) + df_n['err_new'].apply(lambda l:l.tolist())
corps = df_n['corp'].map(' '.join)
df_n['corp']

C:\Users\Mirnalini\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

0    [SGER, 2345R]
1    [SGER, 2345R]
2    [SGRE, 6533R]
3    [SGRE, 5945R]
4    [SGHF, 6754R]
5    [SGAA, 7635R]
Name: corp, dtype: object

In [18]:
#Creating BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corps).toarray()

In [19]:
X

array([[1, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [20]:
#dfn_copy = df_n.copy()
df_n.reset_index(drop=True, inplace=True)
df_n

,Resolution,Scr_new,err_new,corp
0,"Change ""Y"" to N",[SGER],[2345R],"[SGER, 2345R]"
1,"P;ease provde a proper value and Enter ""Y"" to N",[SGER],[2345R],"[SGER, 2345R]"
2,Withdraw the transaction,[SGRE],[6533R],"[SGRE, 6533R]"
3,Process SGAP Screen,[SGRE],[5945R],"[SGRE, 5945R]"
4,"Server issue, so try after sometime",[SGHF],[6754R],"[SGHF, 6754R]"
5,"Server issue, so try after sometime",[SGAA],[7635R],"[SGAA, 7635R]"

In [21]:
#importing libraries and creating objects
import nltk
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer
ps=PorterStemmer()

from nltk.stem import WordNetLemmatizer 
ls= WordNetLemmatizer()

import re

In [75]:
#Cleaning y variable
corpy = []
for e in range(0,len(df_n)):
    resol = re.sub('[^a-zA-Z]',' ',df_n['Resolution'][e])
    resol = resol.lower()
    resol = resol.split()
    #resol = [ps.stem(word) for word in resol if not word in stopwords.words('english')]
    resol = [ls.lemmatize(word) for word in resol if not word in stopwords.words('english')]
    print(resol)
    resol = ' '.join(resol)
    print(resol)
    corpy.append(resol)
    print(corpy)

['change', 'n']
change n
['change n']
['p', 'ease', 'provde', 'proper', 'value', 'enter', 'n']
p ease provde proper value enter n
['change n', 'p ease provde proper value enter n']
['withdraw', 'transaction']
withdraw transaction
['change n', 'p ease provde proper value enter n', 'withdraw transaction']
['process', 'sgap', 'screen']
process sgap screen
['change n', 'p ease provde proper value enter n', 'withdraw transaction', 'process sgap screen']
['server', 'issue', 'try', 'sometime']
server issue try sometime
['change n', 'p ease provde proper value enter n', 'withdraw transaction', 'process sgap screen', 'server issue try sometime']
['server', 'issue', 'try', 'sometime']
server issue try sometime
['change n', 'p ease provde proper value enter n', 'withdraw transaction', 'process sgap screen', 'server issue try sometime', 'server issue try sometime']

In [74]:
df_n['labels'] = corpy

C:\Users\Mirnalini\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [1]:
import pandas as pd
y = pd.get_dummies(df_n['labels'])

y = y.iloc[:,1].values
y

NameError: name 'df_n' is not defined

In [83]:
#Train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)
print("X_train \n",X_train)
print("y_train \n",y_train)
print("X_test \n",X_test)
print("y_test \n",y_test)

X_train
 [[1 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 1 0]]
y_train
 [0 0 0 0]
X_test
 [[0 0 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 0 1]]
y_test
 [0 1]

In [84]:
#Model
from sklearn.naive_bayes import MultinomialNB
sn_model =MultinomialNB().fit(X_train,y_train)
y_pred = sn_model.predict(X_test)
print("y_prd \n",y_pred)

y_prd
 [0 0]

In [85]:
from sklearn.metrics import confusion_matrix,classification_report
matrix1 = confusion_matrix(y_test,y_pred)
matrix2 = classification_report(y_test,y_pred)
print(matrix2)
print(matrix1)

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

[[1 0]
 [1 0]]

C:\Users\Mirnalini\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [50]:
#import imblearn
#from imblearn.over_sampling import SMOTE 
#sm = SMOTE(k_neighbors=1) 
#sm = SMOTE(random_state=0)
#X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

In [29]:
print(X_train)

[[1 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 1 0]]

In [55]:
print(X_test)

[[0 0 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 0 1]]

In [56]:
print(y_train)

[1 0 0 0]

In [57]:
print(y_test)

[0 0]

In [58]:
print(y_pred)

[0 0]

In [59]:
print(corpy)

['changen', 'peaseprovdepropervalueentern', 'withdrawtransaction', 'processsgapscreen', 'serverissuetrysometime', 'serverissuetrysometime']

In [60]:
print(y)

[0 1 0 0 0 0]

In [1]:
df_n

NameError: name 'df_n' is not defined

In [1]:


#Let's say we have a country column. First, you must convert your column to categorical data type:

df.country = df.country.astype('category')

#Get codes for each value as an array:

df.country.cat.codes

#Convert the codes array back to strings

df.country.cat.categories[df.country.cat.codes]

#You can also pass a list of integers

df.country.cat.categories[[0, 1, 2]]

#Or a single code
df.country.cat.categories[0]



#If you run this:

df["column_category"].cat.categories.get_loc("item")

#It will return the code (e.g 0) that corresponds to the "item" in the mapping.

#If you run this:

df["column_category"].cat.categories[0]

#It will return the value of the code (e.g "item") that corresponds to the position 0 of the mapping

NameError: name 'df' is not defined

In [2]:
pwd

'C:\\Users\\Mirnalini'