In [203]:
#Service now data in form of Dict

data = {"result" :
[
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '1',
'resolution' : "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '2',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '3',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '4',
'resolution' :  "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '5',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '6',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '7',
'resolution' :  "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '8',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '9',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '10',
'resolution' :  "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '11',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '12',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '13',
'resolution' :  "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '14',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '15',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '16',
'resolution' :  "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '17',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '18',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '19',
'resolution' : "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '20',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '21',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '22',
'resolution' :  "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '23',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '24',
'resolution' : 'Withdraw transaction'
},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '25',
'resolution' : "Change 'Y' to N "
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '26',
'resolution' : 'Process SGAP Screen'
},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '27',
'resolution' : 'Withdraw transaction'
}
]
}

In [204]:
#Take Copy of dict
import json
import pandas as pd
data_co = data.copy()

In [205]:
#creating dataframe from dict
import pandas as pd
import re
pd.options.display.max_colwidth=100

vals = []
for j in data_co['result']:
    cols = j.keys()
    vals.append(j.values())
sn = pd.DataFrame(data=vals,columns = cols)
sn

                                  sd value INC_NO            resolution
0            sGAB is 1234r throwing   #f00      1      Change 'Y' to N
1   SGCD is facing Err code of 5678R  #0ff      2   Process SGAP Screen
2   SGEF is facing Err code of 9012R  #0ff      3  Withdraw transaction
3            sGAB is 1234r throwing   #f00      4      Change 'Y' to N
4   SGCD is facing Err code of 5678R  #0ff      5   Process SGAP Screen
5   SGEF is facing Err code of 9012R  #0ff      6  Withdraw transaction
6            sGAB is 1234r throwing   #f00      7      Change 'Y' to N
7   SGCD is facing Err code of 5678R  #0ff      8   Process SGAP Screen
8   SGEF is facing Err code of 9012R  #0ff      9  Withdraw transaction
9            sGAB is 1234r throwing   #f00     10      Change 'Y' to N
10  SGCD is facing Err code of 5678R  #0ff     11   Process SGAP Screen
11  SGEF is facing Err code of 9012R  #0ff     12  Withdraw transaction
12           sGAB is 1234r throwing   #f00     13      Change 'Y' to N
13  SGCD is facing Err code of 5678R  #0ff     14   Process SGAP Screen
14  SGEF is facing Err code of 9012R  #0ff     15  Withdraw transaction
15           sGAB is 1234r throwing   #f00     16      Change 'Y' to N
16  SGCD is facing Err code of 5678R  #0ff     17   Process SGAP Screen
17  SGEF is facing Err code of 9012R  #0ff     18  Withdraw transaction
18           sGAB is 1234r throwing   #f00     19      Change 'Y' to N
19  SGCD is facing Err code of 5678R  #0ff     20   Process SGAP Screen
20  SGEF is facing Err code of 9012R  #0ff     21  Withdraw transaction
21           sGAB is 1234r throwing   #f00     22      Change 'Y' to N
22  SGCD is facing Err code of 5678R  #0ff     23   Process SGAP Screen
23  SGEF is facing Err code of 9012R  #0ff     24  Withdraw transaction
24           sGAB is 1234r throwing   #f00     25      Change 'Y' to N
25  SGCD is facing Err code of 5678R  #0ff     26   Process SGAP Screen
26  SGEF is facing Err code of 9012R  #0ff     27  Withdraw transaction

In [206]:
#Extracting screen name from description

def func_ex(pat,lst):
    sub_lst = []
    sear = re.findall(pat,lst,re.IGNORECASE)
    if sear == None:
        return np.nan
    else:
        sub_lst = [i for i,j in sear]
        return sub_lst
pattern1 = r'((sg)[a-zA-Z]{2})'
sn['Scr_new'] = sn['sd'].apply(lambda i:func_ex(pattern1,i))

In [207]:
#Extracting error codefrom description

def func_ex1(pat,lst):
    sub_lst1 = []
    sear = re.findall(pat,lst)
    if sear == None:
        return np.nan
    else:
        return sear
pattern2 = r'[0-9]{4}[R|r]'
sn['err_new'] = sn['sd'].apply(lambda i:func_ex1(pattern2,i))

In [208]:
#Capitalise elements in list
def capill(r):
    newz=[]
    map_object = map(str.upper,r)     
    newz = list(map_object)
    return newz

sn.Scr_new = sn.Scr_new.apply(capill)
sn.err_new = sn.err_new.apply(capill)

sn1 = sn.copy()
sn1

,sd,value,INC_NO,resolution,Scr_new,err_new
0,sGAB is 1234r throwing,#f00,1,Change 'Y' to N,[SGAB],[1234R]
1,SGCD is facing Err code of 5678R,#0ff,2,Process SGAP Screen,[SGCD],[5678R]
2,SGEF is facing Err code of 9012R,#0ff,3,Withdraw transaction,[SGEF],[9012R]
3,sGAB is 1234r throwing,#f00,4,Change 'Y' to N,[SGAB],[1234R]
4,SGCD is facing Err code of 5678R,#0ff,5,Process SGAP Screen,[SGCD],[5678R]
5,SGEF is facing Err code of 9012R,#0ff,6,Withdraw transaction,[SGEF],[9012R]
6,sGAB is 1234r throwing,#f00,7,Change 'Y' to N,[SGAB],[1234R]
7,SGCD is facing Err code of 5678R,#0ff,8,Process SGAP Screen,[SGCD],[5678R]
8,SGEF is facing Err code of 9012R,#0ff,9,Withdraw transaction,[SGEF],[9012R]
9,sGAB is 1234r throwing,#f00,10,Change 'Y' to N,[SGAB],[1234R]
10,SGCD is facing Err code of 5678R,#0ff,11,Process SGAP Screen,[SGCD],[5678R]
11,SGEF is facing Err code of 9012R,#0ff,12,Withdraw transaction,[SGEF],[9012R]
12,sGAB is 1234r throwing,#f00,13,Change 'Y' to N,[SGAB],[1234R]
13,SGCD is facing Err code of 5678R,#0ff,14,Process SGAP Screen,[SGCD],[5678R]
14,SGEF is facing Err code of 9012R,#0ff,15,Withdraw transaction,[SGEF],[9012R]
15,sGAB is 1234r throwing,#f00,16,Change 'Y' to N,[SGAB],[1234R]
16,SGCD is facing Err code of 5678R,#0ff,17,Process SGAP Screen,[SGCD],[5678R]
17,SGEF is facing Err code of 9012R,#0ff,18,Withdraw transaction,[SGEF],[9012R]
18,sGAB is 1234r throwing,#f00,19,Change 'Y' to N,[SGAB],[1234R]
19,SGCD is facing Err code of 5678R,#0ff,20,Process SGAP Screen,[SGCD],[5678R]
20,SGEF is facing Err code of 9012R,#0ff,21,Withdraw transaction,[SGEF],[9012R]
21,sGAB is 1234r throwing,#f00,22,Change 'Y' to N,[SGAB],[1234R]
22,SGCD is facing Err code of 5678R,#0ff,23,Process SGAP Screen,[SGCD],[5678R]
23,SGEF is facing Err code of 9012R,#0ff,24,Withdraw transaction,[SGEF],[9012R]
24,sGAB is 1234r throwing,#f00,25,Change 'Y' to N,[SGAB],[1234R]
25,SGCD is facing Err code of 5678R,#0ff,26,Process SGAP Screen,[SGCD],[5678R]
26,SGEF is facing Err code of 9012R,#0ff,27,Withdraw transaction,[SGEF],[9012R]

In [209]:
#sn1['corp'] = sn1['Scr_new'].apply(lambda l:l) + sn['err_new'].apply(lambda l:l)
#corps = sn1['corp'].map(' '.join)

# Function to combine screen code and error code
def combo(combi):
    combi['corp'] = combi['Scr_new'].apply(lambda l:l) + combi['err_new'].apply(lambda l:l)
    
combo(sn1)
corps = sn1['corp'].map(' '.join)

In [98]:
cols = ['sd', 'value', 'INC_NO','Scr_new','err_new']
sn1.drop(columns=cols,inplace=True)

In [104]:
#Duplicate removal of elements in list if any
#import numpy as pd
#df.Scr_new = df.Scr_new.map(pd.unique)
#df.err_new = df.err_new.map(pd.unique)
#sn1
#sn1.Scr_new.astype('string').value_counts()

#df['lg'] = df['Scr_new'].apply(lambda c : len(c))

#df_n.drop(columns=['lg'],inplace=True)
#df_n.drop(columns=['Description'],inplace=True)
#df_n

#df_n = df[df['lg'] < 2]
#sn1.columns
sn1

              resolution           corp
0       Change 'Y' to N   [SGAB, 1234R]
1    Process SGAP Screen  [SGCD, 5678R]
2   Withdraw transaction  [SGEF, 9012R]
3       Change 'Y' to N   [SGAB, 1234R]
4    Process SGAP Screen  [SGCD, 5678R]
5   Withdraw transaction  [SGEF, 9012R]
6       Change 'Y' to N   [SGAB, 1234R]
7    Process SGAP Screen  [SGCD, 5678R]
8   Withdraw transaction  [SGEF, 9012R]
9       Change 'Y' to N   [SGAB, 1234R]
10   Process SGAP Screen  [SGCD, 5678R]
11  Withdraw transaction  [SGEF, 9012R]
12      Change 'Y' to N   [SGAB, 1234R]
13   Process SGAP Screen  [SGCD, 5678R]
14  Withdraw transaction  [SGEF, 9012R]
15      Change 'Y' to N   [SGAB, 1234R]
16   Process SGAP Screen  [SGCD, 5678R]
17  Withdraw transaction  [SGEF, 9012R]
18      Change 'Y' to N   [SGAB, 1234R]
19   Process SGAP Screen  [SGCD, 5678R]
20  Withdraw transaction  [SGEF, 9012R]
21      Change 'Y' to N   [SGAB, 1234R]
22   Process SGAP Screen  [SGCD, 5678R]
23  Withdraw transaction  [SGEF, 9012R]
24      Change 'Y' to N   [SGAB, 1234R]
25   Process SGAP Screen  [SGCD, 5678R]
26  Withdraw transaction  [SGEF, 9012R]

In [100]:
#Creating BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corps)
print(cv.vocabulary_)

{'sgab': 3, '1234r': 0, 'sgcd': 4, '5678r': 1, 'sgef': 5, '9012r': 2}

In [101]:
#print(X)

In [110]:
#creating tf-idf
from sklearn.feature_extraction.text import TfidfTransformer
tfi = TfidfTransformer().fit(X)
#print(tfi)

tfid = tfi.transform(X)

In [103]:
#importing libraries and creating objects
import nltk
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer
ps=PorterStemmer()

from nltk.stem import WordNetLemmatizer 
ls= WordNetLemmatizer()

import re

In [105]:
#Cleaning y variable
corpy = []
for e in range(0,len(sn1)):
    resol = re.sub('[^a-zA-Z]',' ',sn1['resolution'][e])
    resol = resol.lower()
    resol = resol.split()
    #resol = [ps.stem(word) for word in resol if not word in stopwords.words('english')]
    resol = [ls.lemmatize(word) for word in resol if not word in stopwords.words('english')]
    #print(resol)
    resol = ' '.join(resol)
    #print(resol)
    corpy.append(resol)
    #print(corpy)

In [106]:
sn1['labels'] = corpy
sn1

              resolution           corp                labels
0       Change 'Y' to N   [SGAB, 1234R]              change n
1    Process SGAP Screen  [SGCD, 5678R]   process sgap screen
2   Withdraw transaction  [SGEF, 9012R]  withdraw transaction
3       Change 'Y' to N   [SGAB, 1234R]              change n
4    Process SGAP Screen  [SGCD, 5678R]   process sgap screen
5   Withdraw transaction  [SGEF, 9012R]  withdraw transaction
6       Change 'Y' to N   [SGAB, 1234R]              change n
7    Process SGAP Screen  [SGCD, 5678R]   process sgap screen
8   Withdraw transaction  [SGEF, 9012R]  withdraw transaction
9       Change 'Y' to N   [SGAB, 1234R]              change n
10   Process SGAP Screen  [SGCD, 5678R]   process sgap screen
11  Withdraw transaction  [SGEF, 9012R]  withdraw transaction
12      Change 'Y' to N   [SGAB, 1234R]              change n
13   Process SGAP Screen  [SGCD, 5678R]   process sgap screen
14  Withdraw transaction  [SGEF, 9012R]  withdraw transaction
15      Change 'Y' to N   [SGAB, 1234R]              change n
16   Process SGAP Screen  [SGCD, 5678R]   process sgap screen
17  Withdraw transaction  [SGEF, 9012R]  withdraw transaction
18      Change 'Y' to N   [SGAB, 1234R]              change n
19   Process SGAP Screen  [SGCD, 5678R]   process sgap screen
20  Withdraw transaction  [SGEF, 9012R]  withdraw transaction
21      Change 'Y' to N   [SGAB, 1234R]              change n
22   Process SGAP Screen  [SGCD, 5678R]   process sgap screen
23  Withdraw transaction  [SGEF, 9012R]  withdraw transaction
24      Change 'Y' to N   [SGAB, 1234R]              change n
25   Process SGAP Screen  [SGCD, 5678R]   process sgap screen
26  Withdraw transaction  [SGEF, 9012R]  withdraw transaction

In [137]:
#Taking label variable to y
y = sn1['labels']

In [138]:
#Train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(tfid,y,test_size=0.50,random_state=0)
#print("X_train \n",X_train)
#print("y_train \n",y_train)
#print("X_test \n",X_test)
#print("y_test \n",y_test)

In [139]:
#Applying Naive bayes Model

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train,y_train)

In [140]:
#Predicting using Naive Bayes model
predic = model.predict(X_test)

In [141]:
#Accuracy

from sklearn.metrics import confusion_matrix,classification_report
matrix1 = confusion_matrix(y_test,predic)
matrix2 = classification_report(y_test,predic)
print(matrix1)
print(matrix2)

[[1 0 0]
 [0 5 0]
 [8 0 0]]
                      precision    recall  f1-score   support

            change n       0.11      1.00      0.20         1
 process sgap screen       1.00      1.00      1.00         5
withdraw transaction       0.00      0.00      0.00         8

            accuracy                           0.43        14
           macro avg       0.37      0.67      0.40        14
        weighted avg       0.37      0.43      0.37        14

C:\Users\Mirnalini\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [144]:
# New Input data 
inp_data = {"result" :
[
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '1A'
},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '2A'

},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '3A'

},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '4A'

},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '5A'

},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '6A'

},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '7A'

},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '8A'

},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '9A'

},
{
'sd': 'sGAB is 1234r throwing ',
'value': '#f00',
'INC_NO' : '10A'

},
{
'sd': 'SGCD is facing Err code of 5678R',
'value': '#0ff',
    'INC_NO' : '11A'

},
{
'sd': 'SGEF is facing Err code of 9012R',
'value': '#0ff',
    'INC_NO' : '12A'

}
]
}

In [202]:
#Taking copy of input
dd = inp_data.copy()

import pandas as pd
import re
pd.options.display.max_colwidth=100

#Creating dataframe from dict

val = []
for k in dd['result']:
    col = k.keys()
    val.append(k.values())
inp = pd.DataFrame(data=val,columns = col)
#inp

In [150]:
# Taking copy of dataframe
inp1 = inp.copy()

In [201]:
#Dropping unwanted columns

#inp1.drop(columns=['value'],inplace=True)

In [152]:
#Calling func to extract screen names
inp1['Scr_new'] = inp1['sd'].apply(lambda i:func_ex(pattern1,i))

In [153]:
#Calling func to extract error code
inp1['err_new'] = inp1['sd'].apply(lambda i:func_ex1(pattern2,i))

In [154]:
#Calling func to capitalise words
inp1.Scr_new = inp1.Scr_new.apply(capill)
inp1.err_new = inp1.err_new.apply(capill)

In [167]:
# Drop the unwanted columns
#inp1.drop(columns=['sd'],inplace=True)

In [185]:
# Function to combine screen code and error code
combo(inp1)
inp1
corp_in = inp1['corp'].map(' '.join)

In [199]:
# Applying BOW and Tf-Idf
X_in = cv.fit_transform(corp_in)
tfi_in = TfidfTransformer().fit(X_in)
tfid_in = tfi_in.transform(X_in)
#print(tfid_in)

In [187]:
#Predicting using Naive Bayes model craeted earlier
pred_in = model.predict(X_in)
inp1['output'] = pred_in

In [200]:
#Accuracy - how to
inp1['output'] = pred_in
#inp1

In [194]:
# End results exporting to excel
col_in = ['Scr_new','err_new','corp']
#inp1.drop(columns=col_in,inplace=True)

In [198]:
# Extracting data to excel
inp1.to_excel('incident_resolutions.xlsx',sheet_name='Sheet2')